### ISSUE TITLE
Sass arguments as map

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#542]
We could use Sass arguments as a map. Two possibilities are described below.

### Parser
We could create a parser for a map with properties.

```scss
@mixin parse($declarations) {
  @each $property, $value in $declarations {
    $property: map-get($args, $property);
  }
}
```
Which would allow us to create mixins like these:
```scss
@mixin btn($args) {
  $defaults: (
    'background-color': $light-background,
    'color': $text-color,
  );
  
  @include parse(map-merge($defaults, $args));
}
```

### Without parser
Or we could do something like this to avoid giving too much freedom to developers.

```scss
@mixin btn($args) {
  $declarations: map-merge((
    'background-color': $light-background,
    'color': $text-color,
  ), $args);

  background-color: map-get($declarations, 'background-color');
  color: map-get($declarations, 'color');
}
```

Not sure about the pro's and con's. Would love to hear ideas.
